str1 = input("Enter first string: ")
str2 = input("Enter second string: ")

print("Concatination")
print(str1+str2)
print()
print("Uppercase")
print(str1.upper())
print()
print("Lowercase")
print(str2.lower())
print()
print("Capitalize")
print(str1.capitalize())
print()
print("Strip")
print(str2.strip())
print()
print("Length")
print(len(str1))
print()
print("Title")
print(str1.title())
print()
print("Slicing")
print(str1[0:3:1])
print()
print("Reverse")
print(str1[len(str1):0:-1])
print()
print("Check if is digit")
print(str1.isdigit())